version: '3.8'
services:
  remix-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3036:3000"
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    networks:
      - vn-shared-network

networks:
  vn-shared-network:
    external: true